import process from "process";
import builtins from "builtin-modules";
import esbuild from "esbuild";
import { copyFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = process.argv[2] === "production";

/**
 * 构建后自动拷贝到的 Obsidian 库列表。
 * 每个库都会把 main.js / manifest.json / versions.json 拷入
 * <库路径>/.obsidian/plugins/category-autofill/。
 * 要增加或更换库，修改这个数组即可。
 */
const VAULT_PATHS = ["E:/GithubProgect/MyRunProject/dumplingandcakeblog/src"];

function copyToVaults() {
	for (const vaultPath of VAULT_PATHS) {
		const pluginDir = join(
			vaultPath,
			".obsidian",
			"plugins",
			"category-autofill",
		);
		try {
			mkdirSync(pluginDir, { recursive: true });
			for (const file of ["main.js", "manifest.json", "versions.json"]) {
				copyFileSync(file, join(pluginDir, file));
			}
			console.log(`[copy-to-vault] 已拷贝到 ${pluginDir}`);
		} catch (error) {
			console.warn(
				`[copy-to-vault] 拷贝到 ${pluginDir} 失败（库不存在或占用中？）：`,
				error,
			);
		}
	}
}

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [
		{
			name: "copy-to-vault",
			setup(build) {
				build.onEnd(() => copyToVaults());
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
